// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDw5B3PzaFqfTQ7cxoS-6CP_lIlulCPQ',
    appId: '1:912977426729:web:fd775a7fa20403072e5f38',
    messagingSenderId: '912977426729',
    projectId: 'biometric-app-bad2a',
    authDomain: 'biometric-app-bad2a.firebaseapp.com',
    storageBucket: 'biometric-app-bad2a.appspot.com',
    measurementId: 'G-Y1E3PZT7PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXZKyftUEHs22Sn1cCJf4gmRT8ONC0qY',
    appId: '1:912977426729:android:cee5910796c381762e5f38',
    messagingSenderId: '912977426729',
    projectId: 'biometric-app-bad2a',
    storageBucket: 'biometric-app-bad2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMqmYyjTVlKLOCa17PLQblxa39QUBpccI',
    appId: '1:912977426729:ios:0051cf6927b387492e5f38',
    messagingSenderId: '912977426729',
    projectId: 'biometric-app-bad2a',
    storageBucket: 'biometric-app-bad2a.appspot.com',
    iosBundleId: 'com.example.biometricApp',
  );
}
